version: '3.7'

services:
    app:
        build: 
            context: ./app
            dockerfile: Dockerfile
        volumes:
            - './app:/usr/src/app'
        environment: 
            - FLASK_CONFIG=development
            - FLASK_ENV=development
            - APP_SETTINGS=project.config.BaseConfig
            - SECRET_KEY=ZQbn05PDeA7v11
        ports:
            - 5000:5000
        depends_on:
            - db
    db:
        image: postgres:10
        env_file: .env
        ports:
            - 5432